### ISSUE TITLE
Hot code reload for Service Worker

### ISSUE THREAD

**Issue by kael** [bbhlondon/cra-append-sw#16]
Wondering if it can be easily integrated with CRA live reload system, similarly to what [StencilJS](https://stenciljs.com/docs/service-workers) does, as soon as the service worker is edited, the updated version is copied in the `www` folder.

Is there a way to watch for the service worker updates and have it automatically copied in the destination folder (without ejecting would be nice, I'm new to React) ?

**Comment by tszarzynski** [comment]
@kael It is definitely possible, but beyond the scope of this package. The solution will depend on the rest of your development setup & tooling. Not sure I can come up with a solution that will make everyone happy without overcomplicating things.

Have a look at [run-when-changed](https://www.npmjs.com/package/run-when-changed) for example. Should make it pretty easy.
