### ISSUE TITLE
npmjs wrong version?

### ISSUE THREAD

**Issue by sizeak** [bbhlondon/cra-append-sw#17]
Hi,

The package downloaded from npmjs for 2.6.0 seems to be different from the 2.6.0 tag here. The npmjs version is still using the old preset, in fact it doesn't look like it was updated at all!

**Comment by tszarzynski** [comment]
@sizeak I think I did something silly last time when I was publish the package. I cleaned the mess and published new version which works correctly ( v2.6.1 ).
