### ISSUE TITLE
Use this to replace default service-worker.js file?

### ISSUE THREAD

**Issue by redixhumayun** [bbhlondon/cra-append-sw#4]
Hi, I can see that you've intended this tool to be used to append code onto the service-worker.js file provided by the cra build. 
I'm curious to know whether I can use this tool to replace the service-worker.js file entirely and replace it with my custom one?

**Comment by tszarzynski** [comment]
@redixhumayun I've added a new output mode `replace` that should do what you are asking for. Make sure you are using v2.2.0 and lemme know if it's ok.

**Comment by redixhumayun** [comment]
Brilliant! Love your tool btw! I'm amazed it hasn't received more attention considering how ridiculously complex it is to edit or create a service worker with the CRA build.

**Comment by redixhumayun** [comment]
Out of curiosity, do you know if its possible to run the service worker file from the dev environment? I know cra has a no-op file for the dev environment, is there a way to override that?

**Comment by tszarzynski** [comment]
@redixhumayun It should be possible if you tinker with `registerServiceWorker.js` file. You should be able to disable "production" only condition there.
