### ISSUE TITLE
The same error as CRA showing using your cra-append-sw

### ISSUE THREAD

**Issue by danilosilvadev** [bbhlondon/cra-append-sw#9]
This is the error:

> Unhandled Rejection (TypeError): Cannot read property 'showNotification' of undefined

And this is the custom-sw.js:  

```

Notification.requestPermission(function(status) {
    console.log('Notification permission status:', status);
  });
  
  export function displayNotification() {
    if (Notification.permission === 'granted') {
      console.log('entrou')
      navigator.serviceWorker.getRegistration().then(function(reg) {
        reg.showNotification('Hello world!');
      });
    }
  }
```

My configuration at package.json

> "dependencies": {
>     "cra-append-sw": "^2.3.0",
>     "react": "^16.3.2",
>     "react-burger-menu": "^2.4.2",
>     "react-dom": "^16.3.2",
>     "react-scripts": "1.1.4"
>   },
>   "scripts": {
>     "start": "react-scripts start && cra-append-sw --mode dev ./src/custom-sw.js",
>     "build": "react-scripts build && cra-append-sw ./src/custom-sw.js",

**Comment by tszarzynski** [comment]
Not sure that's a problem with the script itself. Are you sure you're registering SW successfully?
